version: '3'

services:

  load-balance-system:
    image: load-balance-system:latest
    build: .
    container_name: load-balance
    environment:
      MESSAGE_DB_HOST: db
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: test_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
    driver: local